
-- ---------------------------- TF1 aval --------------------------- --
--                                                                  --
--                  SCRIPT DE CRIACAO (DDL)                     --
--                                                                  --
-- Data Criacao ..........: 29/11/2018                              --
-- Autor(es) .............: Lucas Machado de Moura e Silva          --
--                          Ícaro Oliveira                          --
-- Banco de Dados ........: MySQL                                   --
-- Base de Dados(nome) ...: homecare                                --
--                                                                  --
-- Data Ultima Alteracao ..: 04/12/2018                                       --
--                                                                  --
-- PROJETO => 1  Base de Dados                                      --
--      => 26 Tabelas                                           --
--                                                                  --
-- ----------------------------------------------------------------- --

CREATE DATABASE IF NOT EXISTS homecare;
USE homecare; 

CREATE TABLE IF NOT EXISTS COMPLEXIDADE (
	idComplexidade INT AUTO_INCREMENT NOT NULL,
    valorBase DECIMAL(7,2) NOT NULL,
    nivel CHAR(1) NOT NULL UNIQUE,
    descricao VARCHAR(100) NOT NULL,
    CONSTRAINT COMPLEXIDADE_PK PRIMARY KEY(idComplexidade)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS ESTADOCIVIL (
    idEstadoCivil INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(10) NOT NULL,
    CONSTRAINT ESTADOCIVIL_PK PRIMARY KEY (idEstadoCivil)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PATOLOGIA (
    cid VARCHAR(15) NOT NULL,
    nome VARCHAR(300) NOT NULL,
    CONSTRAINT PATOLOGIA_PK PRIMARY KEY (cid)
)DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PESSOA (
    idPessoa INT AUTO_INCREMENT NOT NULL,
    tituloEleitor VARCHAR(30) UNIQUE,
    dataNascimento DATE NOT NULL,
    rg VARCHAR(9) UNIQUE,
    cpf VARCHAR(11) UNIQUE,
    nome VARCHAR(200) NOT NULL,
    cep VARCHAR(8) NOT NULL,
    cidade VARCHAR(30) NOT NULL,
    rua VARCHAR(100) NOT NULL,
    numero INT NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    sexo CHAR NOT NULL,
    idEstadoCivil INT NOT NULL,
    CONSTRAINT PESSOA_PK PRIMARY KEY(idPessoa),
    CONSTRAINT PESSOA_ESTADOCIVL_FK FOREIGN KEY (idEstadoCivil)REFERENCES ESTADOCIVIL (idEstadoCivil) ON DELETE RESTRICT
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PACIENTE (
    idPaciente INT NOT NULL,
    peso DECIMAL(7,2) NOT NULL,
    altura INT NOT NULL,
    tipoSanguineo CHAR(2) NOT NULL,
    diagnostico TEXT,
    idComplexidade INT NOT NULL,
    CONSTRAINT PACIENTE_PK PRIMARY KEY (idPaciente),
    CONSTRAINT PACIENTE_PESSOA_FK FOREIGN KEY (idPaciente) REFERENCES PESSOA(idPessoa) ON DELETE CASCADE,
    CONSTRAINT PACIENTE_COMPLEXIDADE_FK FOREIGN KEY (idComplexidade) REFERENCES COMPLEXIDADE(idComplexidade) ON DELETE RESTRICT
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS CATEGORIAPROFISSIONAL (
    idCategoriaProfissional INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(20) NOT NULL,
    CONSTRAINT CATEGORIAPROFISSIONAL PRIMARY KEY (idCategoriaProfissional)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS CARGO (
	idCargo INT AUTO_INCREMENT NOT NULL,    
	nome VARCHAR(30) NOT NULL,
    CONSTRAINT CARGO_PK PRIMARY KEY (idCargo)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PROFISSIONAL (
    numeroAgencia VARCHAR(10) NOT NULL,
    nomeBanco VARCHAR(20) NOT NULL,
    codBanco INT NOT NULL,
    numeroConta VARCHAR(20) NOT NULL,
    registroProfissional VARCHAR(50) NOT NULL,
    ctps VARCHAR(20) NOT NULL,
    idCargo INT NOT NULL,
    idCategoriaProfissional INT NOT NULL,
    idPessoa INT NOT NULL,
    CONSTRAINT PROFISSIONAL_PK PRIMARY KEY(registroProfissional, idCategoriaProfissional),
    CONSTRAINT PROFISSIONAL_PESSOA_FK FOREIGN KEY(idPessoa) REFERENCES PESSOA(idPessoa) ON DELETE RESTRICT,
    CONSTRAINT PROFISSIONAL_CARGO_FK FOREIGN KEY (idCargo) REFERENCES CARGO(idCargo) ON DELETE RESTRICT,
    CONSTRAINT PROFISSIONAL_CATEGORIAPROFISSIONAL_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES CATEGORIAPROFISSIONAL (idCategoriaProfissional) ON DELETE RESTRICT
)DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS COOPERATIVA (
    cnpj VARCHAR(16) NOT NULL,
    rua VARCHAR(100),
    numero INT,
    cidade VARCHAR(30) NOT NULL,
    bairro VARCHAR(100),
    cep VARCHAR(8) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    CONSTRAINT COOPERATIVA_PK PRIMARY KEY(cnpj)
)DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TECNICO (
	registroProfissional VARCHAR(50) NOT NULL,
    idCategoriaProfissional INT NOT NULL,
    nadaConsta INT NOT NULL,
    cnh VARCHAR(11),
    CONSTRAINT TECNICO_PK PRIMARY KEY(registroProfissional, idCategoriaProfissional),
    CONSTRAINT TECNICO_PROFISSIONAL_REGISTROPROFISSIONAL_FK FOREIGN KEY (registroProfissional) REFERENCES PROFISSIONAL (registroProfissional) ON DELETE CASCADE,
	CONSTRAINT TECNICO_PROFISSIONAL_CATEGORIAPROFISSIONAL_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES PROFISSIONAL (idCategoriaProfissional) ON DELETE CASCADE
)DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TIPOVISITA (
    idTipoVisita INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(30) NOT NULL,
    CONSTRAINT TIPOVISITA_PK PRIMARY KEY(idTipoVisita)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS VISITA (
    idVisita INT AUTO_INCREMENT NOT NULL,
    dataHoraInicio DATETIME NOT NULL,
    dataHoraFim DATETIME NOT NULL,
    idTipoVisita INT NOT NULL,
    idPaciente INT NOT NULL,
    registroProfissional VARCHAR(50) NOT NULL,
    idCategoriaProfissional INT NOT NULL,
    CONSTRAINT VISITA_PK PRIMARY KEY(idVisita),
    UNIQUE KEY TIPO_DATAHORAFIM_DATAHORAINICIO_TIPOVISITA_PROFISSIONAL_UN (dataHoraInicio, dataHorafim, registroProfissional, idCategoriaProfissional),
    UNIQUE KEY TIPO_DATAHORAFIM_DATAHORAINICIO_TIPOVISITA_PACIENTE_UN (dataHoraInicio, dataHorafim, idTipoVisita, idPaciente, idCategoriaProfissional, registroProfissional),
    CONSTRAINT VISITA_TIPVISITA_FK FOREIGN KEY (idTipoVisita) REFERENCES TIPOVISITA (idTipoVisita) ON DELETE RESTRICT,
    CONSTRAINT VISITA_PACIENTE_FK FOREIGN KEY (idPaciente) REFERENCES PACIENTE (idPaciente),
    CONSTRAINT VISITA_REGISTROPROFISSIONAL_PROFISSIONAL_FK FOREIGN KEY (registroProfissional) REFERENCES PROFISSIONAL (registroProfissional),
    CONSTRAINT VISITA_CATEGORIAPROFISSIONAL_PROFISSIONAL_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES PROFISSIONAL (idCategoriaProfissional) ON DELETE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS MEDICAMENTO (
    idMedicamento INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT MEDICAMENTO_PK PRIMARY KEY(idMedicamento)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PRESCRICAO (
    idPrescricao INT AUTO_INCREMENT NOT NULL,
    periodoDeUso VARCHAR(250) NOT NULL,
    posologia VARCHAR(100) NOT NULL,
    observacao VARCHAR(500),
    idVisita INT NOT NULL,
    idMedicamento INT NOT NULL,
    CONSTRAINT PRESCRICAO_PK PRIMARY KEY(idPrescricao),
    CONSTRAINT PRESCRICAO_VISITA_FK FOREIGN KEY (idVisita) REFERENCES VISITA (idVisita) ON DELETE RESTRICT,
    CONSTRAINT PRESCRICAO_MEDICAMENTO_FK FOREIGN KEY (idMedicamento) REFERENCES MEDICAMENTO (idMedicamento) ON DELETE RESTRICT
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS EVOLUCAO (
	dataHoraRegistro TIMESTAMP NOT NULL,
    observacao VARCHAR(500) NOT NULL,
    idVisita INT NOT NULL,
    idPrescricao INT,
    CONSTRAINT EVOLUCAO_PK PRIMARY KEY(dataHoraRegistro, idVisita), 
    CONSTRAINT EVOLUCAO_VISITA_FK FOREIGN KEY (idVisita) REFERENCES VISITA (idVisita) ON DELETE RESTRICT,
    CONSTRAINT EVOLUCAO_PRESCRICAO_FK FOREIGN KEY (idPrescricao) REFERENCES PRESCRICAO (idPrescricao) ON DELETE SET NULL
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS EQUIPAMENTO (
    idEquipamento INT AUTO_INCREMENT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    CONSTRAINT EQUIPAMENTO_PK PRIMARY KEY (idEquipamento)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TELEFONEPESSOA (
    idTelefone INT AUTO_INCREMENT NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    idPessoa INT NOT NULL,
    CONSTRAINT TELEFONEPESSOA_PK PRIMARY KEY(idTelefone),
    CONSTRAINT TELEFONEPESSOA_PESSOA_FK FOREIGN KEY (idPessoa) REFERENCES PESSOA (idPessoa)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TELEFONECOOPERATIVA (
    idTelefone INT AUTO_INCREMENT NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    cnpj VARCHAR(16) NOT NULL,
    CONSTRAINT TELEFONECOOPERATIVA_PK PRIMARY KEY(idTelefone),
    CONSTRAINT TELEFONECOOPERATIVA_COOPERATIVA_FK FOREIGN KEY (cnpj) REFERENCES COOPERATIVA (cnpj)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS AVALIACAO (
    registroProfissional VARCHAR(50),
    idCategoriaProfissional INT NOT NULL,
    idPaciente INT,
    dataAvaliacao TIMESTAMP,
    avaliacao TEXT,
	CONSTRAINT AVALIACAO_PACIENTE_FK FOREIGN KEY (idPaciente) REFERENCES PACIENTE (idPaciente) ON DELETE SET NULL,
    CONSTRAINT AVALIACAO_REGISTROPROFISSIONAL_TECNICO_FK FOREIGN KEY (registroProfissional) REFERENCES TECNICO (registroProfissional) ON DELETE RESTRICT,
	CONSTRAINT AVALIACAO_CATEGORIAPROFISSIONAL_TECNICO_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES TECNICO (idCategoriaProfissional) ON DELETE CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PACIENTE_PATOLOGIA (
    cid VARCHAR(15),
    idPaciente INT,
    CONSTRAINT PACIENTE_PATOLOGIA_PATOLOGIA_FK FOREIGN KEY (cid)REFERENCES PATOLOGIA (cid)ON DELETE RESTRICT,
 	CONSTRAINT PACIENTE_PATOLOGIA_PACIENTE_FK FOREIGN KEY (idPaciente) REFERENCES PACIENTE (idPaciente) ON DELETE RESTRICT
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TECNICO_COOPERATIVA (
    cnpj VARCHAR(16),
    registroProfissional VARCHAR(50),
    idCategoriaProfissional INT NOT NULL,
    CONSTRAINT TECNICO_COOPERATIVA_COOPERATIVA FOREIGN KEY (cnpj) REFERENCES COOPERATIVA (cnpj) ON DELETE RESTRICT,
	CONSTRAINT TECNICO_COOPERATIVA_CATEGORIAPROFISSIONAL_TECNICO_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES TECNICO (idCategoriaProfissional) ON DELETE RESTRICT,
    CONSTRAINT TECNICO_COOPERATIVA_REGISTROPROFISSIONAL_TECNICO_FK FOREIGN KEY (registroProfissional) REFERENCES TECNICO (registroProfissional) ON DELETE RESTRICT
)DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS PACIENTE_EQUIPAMENTO (
    idPaciente INT,
    idEquipamento INT,
    CONSTRAINT PACIENTE_EQUIPAMENTO_PACIENTE FOREIGN KEY (idPaciente) REFERENCES PACIENTE (idPaciente) ON DELETE SET NULL,
    CONSTRAINT PACIENTE_EQUIPAMENTO_EQUIPAMENTO FOREIGN KEY (idEquipamento) REFERENCES EQUIPAMENTO (idEquipamento) ON DELETE SET NULL
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS TECNICO_EQUIPAMENTO (
    registroProfissional VARCHAR(50),
    idCategoriaProfissional INT NOT NULL,
    idEquipamento INT,
    CONSTRAINT TECNICO_EQUIPAMENTO_REGISTROPROFISSIONAL_TECNICO_FK FOREIGN KEY (registroProfissional) REFERENCES TECNICO (registroProfissional) ON DELETE CASCADE,
	CONSTRAINT TECNICO_EQUIPAMENTO_CATEGORIAPROFISSIONAL_TECNICO_FK FOREIGN KEY (idCategoriaProfissional) REFERENCES TECNICO (idCategoriaProfissional) ON DELETE CASCADE,
	CONSTRAINT TECNICO_EQUIPAMENTO_EQUIPAMENTO_FK FOREIGN KEY (idEquipamento) REFERENCES EQUIPAMENTO (idEquipamento) ON DELETE SET NULL
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;

